// Generated by shard-migration notes/cc-P16-tools/gen_layout.py. Do not edit by hand.
//
// design/mine-camp-tents/layout.json, verbatim. The test container holds server/tests but not design/
// (docker/uo/Dockerfile copies only server/customizations, server/tests, server/migrations and
// server/patches), so the design file reaches the test as this copy. Its SHA-256 is checked against
// the hash the generator recorded from the design file.

namespace ShatteredLegacy.Tests;

internal static class MineCampLayoutDesignCopy
{
    public const string Sha256 = "f2fa305dd65ed435474e7f585e4823e6621bd086ff430877cc7ebffd640380d1";

    public const string Json =
"""
{
 "map": "Trammel",
 "source": "design/mine-camp-tents/camp.py; z values are client-side estimates, verify on the server",
 "addons": [
  {
   "name": "MinersCompactTent",
   "components": [
    {
     "group": "tent",
     "id": "0x036F",
     "name": "tent wall",
     "x": 3494,
     "y": 2744,
     "z": 5
    },
    {
     "group": "tent",
     "id": "0x036E",
     "name": "tent wall",
     "x": 3495,
     "y": 2743,
     "z": 5
    },
    {
     "group": "tent",
     "id": "0x036E",
     "name": "tent wall",
     "x": 3496,
     "y": 2743,
     "z": 5
    },
    {
     "group": "tent",
     "id": "0x036D",
     "name": "tent wall",
     "x": 3497,
     "y": 2743,
     "z": 5
    },
    {
     "group": "tent",
     "id": "0x0369",
     "name": "tent wall",
     "x": 3495,
     "y": 2745,
     "z": 5
    },
    {
     "group": "tent",
     "id": "0x0369",
     "name": "tent wall",
     "x": 3496,
     "y": 2745,
     "z": 5
    },
    {
     "group": "tent",
     "id": "0x0368",
     "name": "tent wall",
     "x": 3497,
     "y": 2745,
     "z": 5
    },
    {
     "group": "tent",
     "id": "0x0603",
     "name": "tent roof",
     "x": 3495,
     "y": 2744,
     "z": 19
    },
    {
     "group": "tent",
     "id": "0x0603",
     "name": "tent roof",
     "x": 3496,
     "y": 2744,
     "z": 19
    },
    {
     "group": "tent",
     "id": "0x0633",
     "name": "tent roof",
     "x": 3497,
     "y": 2744,
     "z": 16
    },
    {
     "group": "deco",
     "id": "0x0A58",
     "name": "bedroll",
     "x": 3495,
     "y": 2742,
     "z": 5
    },
    {
     "group": "deco",
     "id": "0x1BF0",
     "name": "iron ingots",
     "x": 3496,
     "y": 2742,
     "z": 5
    },
    {
     "group": "deco",
     "id": "0x1BEF",
     "name": "iron ingot%s",
     "x": 3496,
     "y": 2742,
     "z": 6
    },
    {
     "group": "deco",
     "id": "0x0E77",
     "name": "barrel",
     "x": 3497,
     "y": 2742,
     "z": 5
    },
    {
     "group": "deco",
     "id": "0x0E31",
     "name": "brazier",
     "x": 3499,
     "y": 2742,
     "z": 2
    },
    {
     "group": "deco",
     "id": "0x0E3F",
     "name": "crate",
     "x": 3498,
     "y": 2743,
     "z": 4
    },
    {
     "group": "deco",
     "id": "0x0E86",
     "name": "pickaxe",
     "x": 3498,
     "y": 2743,
     "z": 7
    },
    {
     "group": "deco",
     "id": "0x19B8",
     "name": "iron ore",
     "x": 3499,
     "y": 2743,
     "z": 3
    },
    {
     "group": "deco",
     "id": "0x19BA",
     "name": "iron ore",
     "x": 3500,
     "y": 2743,
     "z": 3
    },
    {
     "group": "deco",
     "id": "0x0FB4",
     "name": "sledge hammer",
     "x": 3500,
     "y": 2744,
     "z": 2
    },
    {
     "group": "deco",
     "id": "0x0F39",
     "name": "shovel",
     "x": 3500,
     "y": 2742,
     "z": 2
    }
   ]
  },
  {
   "name": "SurveyArchivistTent",
   "components": [
    {
     "group": "tent",
     "id": "0x036F",
     "name": "tent wall",
     "x": 3492,
     "y": 2754,
     "z": 5
    },
    {
     "group": "tent",
     "id": "0x036E",
     "name": "tent wall",
     "x": 3493,
     "y": 2753,
     "z": 5
    },
    {
     "group": "tent",
     "id": "0x036E",
     "name": "tent wall",
     "x": 3494,
     "y": 2753,
     "z": 5
    },
    {
     "group": "tent",
     "id": "0x036D",
     "name": "tent wall",
     "x": 3495,
     "y": 2753,
     "z": 5
    },
    {
     "group": "tent",
     "id": "0x0369",
     "name": "tent wall",
     "x": 3493,
     "y": 2755,
     "z": 5
    },
    {
     "group": "tent",
     "id": "0x0369",
     "name": "tent wall",
     "x": 3494,
     "y": 2755,
     "z": 5
    },
    {
     "group": "tent",
     "id": "0x0368",
     "name": "tent wall",
     "x": 3495,
     "y": 2755,
     "z": 5
    },
    {
     "group": "tent",
     "id": "0x0603",
     "name": "tent roof",
     "x": 3493,
     "y": 2754,
     "z": 19
    },
    {
     "group": "tent",
     "id": "0x0603",
     "name": "tent roof",
     "x": 3494,
     "y": 2754,
     "z": 19
    },
    {
     "group": "tent",
     "id": "0x0633",
     "name": "tent roof",
     "x": 3495,
     "y": 2754,
     "z": 16
    },
    {
     "group": "deco",
     "id": "0x0E31",
     "name": "brazier",
     "x": 3496,
     "y": 2756,
     "z": 4
    },
    {
     "group": "deco",
     "id": "0x0B4A",
     "name": "writing table",
     "x": 3497,
     "y": 2753,
     "z": 3
    },
    {
     "group": "deco",
     "id": "0x14EB",
     "name": "map",
     "x": 3497,
     "y": 2753,
     "z": 8
    },
    {
     "group": "deco",
     "id": "0x0A0F",
     "name": "candle",
     "x": 3497,
     "y": 2753,
     "z": 8
    },
    {
     "group": "deco",
     "id": "0x0B5F",
     "name": "bench",
     "x": 3496,
     "y": 2753,
     "z": 4
    },
    {
     "group": "deco",
     "id": "0x1047",
     "name": "globe",
     "x": 3496,
     "y": 2755,
     "z": 4
    },
    {
     "group": "deco",
     "id": "0x0E42",
     "name": "wooden chest",
     "x": 3497,
     "y": 2755,
     "z": 2
    },
    {
     "group": "deco",
     "id": "0x2270",
     "name": "scroll",
     "x": 3497,
     "y": 2755,
     "z": 6
    },
    {
     "group": "deco",
     "id": "0x2272",
     "name": "scroll",
     "x": 3497,
     "y": 2755,
     "z": 6
    },
    {
     "group": "deco",
     "id": "0x09AA",
     "name": "wooden box",
     "x": 3493,
     "y": 2752,
     "z": 6
    },
    {
     "group": "deco",
     "id": "0x1057",
     "name": "sextant",
     "x": 3493,
     "y": 2752,
     "z": 9
    },
    {
     "group": "deco",
     "id": "0x0A59",
     "name": "bedroll",
     "x": 3494,
     "y": 2756,
     "z": 6
    }
   ]
  }
 ],
 "npcs": [
  {
   "type": "MinersCompactLiaison",
   "from": [
    3510,
    2748,
    0
   ],
   "to": [
    3498,
    2744,
    4
   ],
   "facing": "East"
  },
  {
   "type": "SurveyArchivist",
   "from": [
    3516,
    2747,
    1
   ],
   "to": [
    3496,
    2754,
    4
   ],
   "facing": "East"
  }
 ]
}
""";
}
