// Generated by shard-migration notes/cc-P19-tools/gen_office_layout.py. Do not edit by hand.
//
// design/registrar-office/layout.json, verbatim. The test container holds server/tests but not design/
// (docker/uo/Dockerfile copies only server/customizations, server/tests, server/migrations and
// server/patches), so the design file reaches the test as this copy. Its SHA-256 is checked against
// the hash the generator recorded from the design file.

namespace ShatteredLegacy.Tests;

internal static class RegistrarOfficeLayoutDesignCopy
{
    public const string Sha256 = "a68ea589c28aaa5f61a077010866d1f2642388e22fae4bad240b31e6fecda4bf";

    public const string Json =
"""
{
 "map": "Trammel",
 "building": "League of Extraordinary Citizens Field Office (New Haven), walls x3453-3462 y2596-2603, floor z18",
 "source": "design/registrar-office/registrar.py; z values are client-side estimates, verify on the server",
 "components": [
  {
   "area": "outside",
   "id": "0x11C9",
   "name": "potted tree",
   "x": 3458,
   "y": 2595,
   "z": 15
  },
  {
   "area": "outside",
   "id": "0x0B97",
   "name": "wooden signpost",
   "x": 3463,
   "y": 2597,
   "z": 13
  },
  {
   "area": "outside",
   "id": "0x0BCF",
   "name": "wooden sign",
   "x": 3463,
   "y": 2597,
   "z": 13
  },
  {
   "area": "outside",
   "id": "0x0B98",
   "name": "wooden signpost",
   "x": 3460,
   "y": 2595,
   "z": 15
  },
  {
   "area": "outside",
   "id": "0x0BD0",
   "name": "wooden sign",
   "x": 3460,
   "y": 2595,
   "z": 15
  },
  {
   "area": "office",
   "id": "0x1E25",
   "name": "books",
   "x": 3458,
   "y": 2600,
   "z": 24
  },
  {
   "area": "office",
   "id": "0x2D61",
   "name": "inkwell",
   "x": 3458,
   "y": 2601,
   "z": 24
  },
  {
   "area": "office",
   "id": "0x2270",
   "name": "scroll",
   "x": 3458,
   "y": 2601,
   "z": 24
  },
  {
   "area": "office",
   "id": "0x1810",
   "name": "hourglass",
   "x": 3458,
   "y": 2600,
   "z": 27
  },
  {
   "area": "office",
   "id": "0x0A99",
   "name": "bookcase",
   "x": 3461,
   "y": 2597,
   "z": 18
  },
  {
   "area": "office",
   "id": "0x0A9A",
   "name": "bookcase",
   "x": 3458,
   "y": 2602,
   "z": 18
  },
  {
   "area": "office",
   "id": "0x1E5F",
   "name": "bulletin board",
   "x": 3458,
   "y": 2598,
   "z": 18
  },
  {
   "area": "office",
   "id": "0x0B26",
   "name": "candelabra",
   "x": 3461,
   "y": 2600,
   "z": 18
  },
  {
   "area": "office",
   "id": "0x11CA",
   "name": "flowerpot",
   "x": 3460,
   "y": 2597,
   "z": 18
  },
  {
   "area": "office",
   "id": "0x1047",
   "name": "globe",
   "x": 3461,
   "y": 2598,
   "z": 18
  },
  {
   "area": "quarters",
   "id": "0x0E42",
   "name": "wooden chest",
   "x": 3456,
   "y": 2597,
   "z": 18
  },
  {
   "area": "quarters",
   "id": "0x0A9A",
   "name": "bookcase",
   "x": 3454,
   "y": 2602,
   "z": 18
  },
  {
   "area": "quarters",
   "id": "0x2272",
   "name": "scroll",
   "x": 3454,
   "y": 2598,
   "z": 24
  }
 ]
}
""";
}
