// Generated by shard-migration notes/cc-P19-tools/gen_office_layout.py from design/registrar-office/layout.json.
// Do not edit by hand: change the design file and re-run the generator. The test
// RegistrarOfficeVerification.TheLoadedLayoutIsTheDesignFile compares this table with the design file.
//
// The layout is a C# table, not a data file, for cc-P16's reason: the build installs only .cs files from
// server/customizations (docker/uo/apply-patches.sh, mirror_cs_tree), and Distribution/Data is pinned.
// Components use cc-P16's MineCampComponent record (ClusterFMineCampLayout.cs); Group is the design's area.

namespace Server;

public static class ClusterFRegistrarOfficeLayout
{
    public const string DesignFile = "design/registrar-office/layout.json";
    public const string DesignSha256 = "a68ea589c28aaa5f61a077010866d1f2642388e22fae4bad240b31e6fecda4bf";
    public const string MapName = "Trammel";

    // In design order.
    public static readonly MineCampComponent[] Components =
    [
        new("outside", 0x11C9, "potted tree", 3458, 2595, 15),
        new("outside", 0x0B97, "wooden signpost", 3463, 2597, 13),
        new("outside", 0x0BCF, "wooden sign", 3463, 2597, 13),
        new("outside", 0x0B98, "wooden signpost", 3460, 2595, 15),
        new("outside", 0x0BD0, "wooden sign", 3460, 2595, 15),
        new("office", 0x1E25, "books", 3458, 2600, 24),
        new("office", 0x2D61, "inkwell", 3458, 2601, 24),
        new("office", 0x2270, "scroll", 3458, 2601, 24),
        new("office", 0x1810, "hourglass", 3458, 2600, 27),
        new("office", 0x0A99, "bookcase", 3461, 2597, 18),
        new("office", 0x0A9A, "bookcase", 3458, 2602, 18),
        new("office", 0x1E5F, "bulletin board", 3458, 2598, 18),
        new("office", 0x0B26, "candelabra", 3461, 2600, 18),
        new("office", 0x11CA, "flowerpot", 3460, 2597, 18),
        new("office", 0x1047, "globe", 3461, 2598, 18),
        new("quarters", 0x0E42, "wooden chest", 3456, 2597, 18),
        new("quarters", 0x0A9A, "bookcase", 3454, 2602, 18),
        new("quarters", 0x2272, "scroll", 3454, 2598, 24),
    ];

    public static readonly MineCampComponent[] Outside =
    [
        new("outside", 0x11C9, "potted tree", 3458, 2595, 15),
        new("outside", 0x0B97, "wooden signpost", 3463, 2597, 13),
        new("outside", 0x0BCF, "wooden sign", 3463, 2597, 13),
        new("outside", 0x0B98, "wooden signpost", 3460, 2595, 15),
        new("outside", 0x0BD0, "wooden sign", 3460, 2595, 15),
    ];

    public static readonly MineCampComponent[] Office =
    [
        new("office", 0x1E25, "books", 3458, 2600, 24),
        new("office", 0x2D61, "inkwell", 3458, 2601, 24),
        new("office", 0x2270, "scroll", 3458, 2601, 24),
        new("office", 0x1810, "hourglass", 3458, 2600, 27),
        new("office", 0x0A99, "bookcase", 3461, 2597, 18),
        new("office", 0x0A9A, "bookcase", 3458, 2602, 18),
        new("office", 0x1E5F, "bulletin board", 3458, 2598, 18),
        new("office", 0x0B26, "candelabra", 3461, 2600, 18),
        new("office", 0x11CA, "flowerpot", 3460, 2597, 18),
        new("office", 0x1047, "globe", 3461, 2598, 18),
    ];

    public static readonly MineCampComponent[] Quarters =
    [
        new("quarters", 0x0E42, "wooden chest", 3456, 2597, 18),
        new("quarters", 0x0A9A, "bookcase", 3454, 2602, 18),
        new("quarters", 0x2272, "scroll", 3454, 2598, 24),
    ];

    public static readonly (string Area, MineCampComponent[] Components)[] Areas =
    [
        ("outside", Outside),
        ("office", Office),
        ("quarters", Quarters),
    ];
}
