// Generated by shard-migration notes/cc-P16-tools/gen_layout.py from design/mine-camp-tents/layout.json.
// Do not edit by hand: change the design file and re-run the generator. The test
// MineCampVerification.TheLoadedLayoutIsTheDesignFile compares this table with the design file.
//
// The layout is a C# table, not a data file, because the build installs only .cs files from
// server/customizations (docker/uo/apply-patches.sh, mirror_cs_tree), and Distribution/Data is pinned.

namespace Server;

public static class ClusterFMineCampLayout
{
    public const string DesignFile = "design/mine-camp-tents/layout.json";
    public const string DesignSha256 = "f2fa305dd65ed435474e7f585e4823e6621bd086ff430877cc7ebffd640380d1";
    public const string MapName = "Trammel";

    public static readonly MineCampComponent[] MinersCompactTent =
    [
        new("tent", 0x036F, "tent wall", 3494, 2744, 5),
        new("tent", 0x036E, "tent wall", 3495, 2743, 5),
        new("tent", 0x036E, "tent wall", 3496, 2743, 5),
        new("tent", 0x036D, "tent wall", 3497, 2743, 5),
        new("tent", 0x0369, "tent wall", 3495, 2745, 5),
        new("tent", 0x0369, "tent wall", 3496, 2745, 5),
        new("tent", 0x0368, "tent wall", 3497, 2745, 5),
        new("tent", 0x0603, "tent roof", 3495, 2744, 19),
        new("tent", 0x0603, "tent roof", 3496, 2744, 19),
        new("tent", 0x0633, "tent roof", 3497, 2744, 16),
        new("deco", 0x0A58, "bedroll", 3495, 2742, 5),
        new("deco", 0x1BF0, "iron ingots", 3496, 2742, 5),
        new("deco", 0x1BEF, "iron ingot%s", 3496, 2742, 6),
        new("deco", 0x0E77, "barrel", 3497, 2742, 5),
        new("deco", 0x0E31, "brazier", 3499, 2742, 2),
        new("deco", 0x0E3F, "crate", 3498, 2744, 4), // P16-BREAK
        new("deco", 0x0E86, "pickaxe", 3498, 2743, 7),
        new("deco", 0x19B8, "iron ore", 3499, 2743, 3),
        new("deco", 0x19BA, "iron ore", 3500, 2743, 3),
        new("deco", 0x0FB4, "sledge hammer", 3500, 2744, 2),
        new("deco", 0x0F39, "shovel", 3500, 2742, 2),
    ];

    public static readonly MineCampComponent[] SurveyArchivistTent =
    [
        new("tent", 0x036F, "tent wall", 3492, 2754, 5),
        new("tent", 0x036E, "tent wall", 3493, 2753, 5),
        new("tent", 0x036E, "tent wall", 3494, 2753, 5),
        new("tent", 0x036D, "tent wall", 3495, 2753, 5),
        new("tent", 0x0369, "tent wall", 3493, 2755, 5),
        new("tent", 0x0369, "tent wall", 3494, 2755, 5),
        new("tent", 0x0368, "tent wall", 3495, 2755, 5),
        new("tent", 0x0603, "tent roof", 3493, 2754, 19),
        new("tent", 0x0603, "tent roof", 3494, 2754, 19),
        new("tent", 0x0633, "tent roof", 3495, 2754, 16),
        new("deco", 0x0E31, "brazier", 3496, 2756, 4),
        new("deco", 0x0B4A, "writing table", 3497, 2753, 3),
        new("deco", 0x14EB, "map", 3497, 2753, 8),
        new("deco", 0x0A0F, "candle", 3497, 2753, 8),
        new("deco", 0x0B5F, "bench", 3496, 2753, 4),
        new("deco", 0x1047, "globe", 3496, 2755, 4),
        new("deco", 0x0E42, "wooden chest", 3497, 2755, 2),
        new("deco", 0x2270, "scroll", 3497, 2755, 6),
        new("deco", 0x2272, "scroll", 3497, 2755, 6),
        new("deco", 0x09AA, "wooden box", 3493, 2752, 6),
        new("deco", 0x1057, "sextant", 3493, 2752, 9),
        new("deco", 0x0A59, "bedroll", 3494, 2756, 6),
    ];

    public static readonly (string Name, MineCampComponent[] Components)[] Addons =
    [
        ("MinersCompactTent", MinersCompactTent),
        ("SurveyArchivistTent", SurveyArchivistTent),
    ];

    public static readonly MineCampNpcMove[] Npcs =
    [
        new("MinersCompactLiaison", new Point3D(3510, 2748, 0), new Point3D(3498, 2744, 4), Direction.East),
        new("SurveyArchivist", new Point3D(3516, 2747, 1), new Point3D(3496, 2754, 4), Direction.East),
    ];
}

public sealed record MineCampComponent(string Group, int ItemID, string Name, int X, int Y, int Z)
{
    public Point3D Location => new(X, Y, Z);
}

public sealed record MineCampNpcMove(string TypeName, Point3D From, Point3D To, Direction Facing);
